name: Build latex document and deploy to wiki

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: ctleelab-expectations-conduct.tex
          latexmk_use_lualatex: true
          pre_compile: |
            apk add msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ctleelab-expectations-conduct.pdf
    
  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        # Downloads the artifact from the previous job
        uses: actions/download-artifact@v4
      - name: unpack
        run: |
          tar -xvf github-pages/artifact.tar
